apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: giropops-senhas
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/limits-rps: "2"
      #    nginx.ingress.kubernetes.io/auth-type: "basic"
      #    nginx.ingress.kubernetes.io/auth-secret: "giropops-senhas-users"
      #    nginx.ingress.kubernetes.io/auth-realm: "Autenticação Necessária!"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
      #nginx.ingress.kuberneter.io/affinity: "cokie"
      #nginx.ingress.kuberneter.io/session-cokie-name: "giropops-cokie"
      #nginx.ingress.kubernetes.io/upstream-hash-by: "$request-uri"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - giropops.containers.expert
    secretName: giropops-container-expert-tls
  rules:
  - host: giropops.containers.expert
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: giropops-senhas
            port:
              number: 5000
